
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  database: db/jobshub_dev

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  database: db/jobshub_tst

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: 
  password:
  database: db/jobshub_prd
  
  
